spring.application.name=CRUDAlumnos
server.port= 8002

#Conexion a la DB
spring.datasource.url=jdbc:mysql://alan-db.cb0ig0ekwa5y.us-east-2.rds.amazonaws.com:3306/alumnos_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimeZone=UTC
spring.datasource.username=admin
spring.datasource.password=Ruizmtz6712#

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true